org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Mod
mod_id=hungerstrike
mod_name=Hunger Strike
mod_version=9.0.0
mod_group_id=com.jaquadro.minecraft.hungerstrike
mod_authors=Texelsaur
mod_license=MIT
mod_description=Restores pre-hunger health mechanics.

# Platform
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.81
# Lower bound of the NeoForge versions this build is compatible with.
neo_version_range=[26.2.0.59,)
loader_version_range=[3,)
